Rsl 50
Malagor/rs-lang pull request #112
Opened 2021-04-13 21:35 UTC by Andrei107Q

2021-04-14 08:10 UTC, Malagor reviewed
В принципе норм. Подправь комменты и оформляй. Стартовый экран вроде Дима планировал делать, так что его на последок оставляй.

2021-04-14 08:10 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +export const PLAY_PAGE = 'palyPage';
'palyPage'

2021-04-14 08:10 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +  const max1 = Math.floor(max);
А зачем тебе эти округления, ты же всегда целые числа передаешь?
Посмотри тут варианты решения задачи в конце страницы. Там есть 2 варианта
https://learn.javascript.ru/task/random-int-min-max

2021-04-14 08:10 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +  const playFinishSound = () => playSound(FinishSound);
Странная функция. Что мешает просто вставить playSound(FinishSound); куда там нужно?

2021-04-14 08:10 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +        randomNumWordTranslate();
А какой смысл описывать функцию и сразу же ее вызывать? Просто напиши сюда код, который должен отработать. Если бы ты её переиспользовал где-то, а так, смысл в этом?

2021-04-14 20:46 UTC, Andrei107Q commented on src/modules/Sprint/Sprint.tsx
> +export const PLAY_PAGE = 'palyPage';
исправил

2021-04-14 20:47 UTC, Andrei107Q commented on src/modules/Sprint/Sprint.tsx
> +  const max1 = Math.floor(max);
спасибо за подсказку 
исправил

2021-04-14 20:52 UTC, Andrei107Q commented on src/modules/Sprint/Sprint.tsx
> +  const playFinishSound = () => playSound(FinishSound);
исправил

2021-04-14 20:58 UTC, Andrei107Q commented on src/modules/Sprint/Sprint.tsx
> +        randomNumWordTranslate();
я тут же проверяю что бы рандомайзер не выдал мне такое же число как и текущее слово, т.к. тогда будет не правильная логики в словах. и если вдруг так получилось я вызываю функую еще раз на 166 строке. а подругому не знаю как реализовать.

2021-04-15 19:00 UTC, femiarkh reviewed
Используется неправильный селектор слов - слова нужно брать из `gameWords`, а не из учебника. При повторной игре не появляется модальное окно с результатами. 
Из пожеланий: не хватает тикающих звуков. Не помешал бы отсчёт до нуля перед началом игры.

2021-04-15 21:30 UTC, Malagor requested changes
В принципе норм. Поправь пока комменты не касающиеся дизайна. А с Лизой тогда подумайте как быть с картинкой. Я тоже подумаю.

2021-04-15 21:30 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +        randomNumWordTranslate();
Я о вот это функции `randomNumWordTranslate`, которая в блоке `else`. У тебя фактически блок else, это описании функции и сразу же её вызов. ТАк можно просто тело функции в `елсе` запихнуть и все, без лишних телодвижений.

2021-04-15 21:30 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +const TIME_GAME = 60;
Вынеси эту штуку в константы игры. Назови как-то по типу SPRINT_TIME_GAME

2021-04-15 21:30 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +export const RESULTS_PAGE = 'resultsPage';
Что-то они у тебя местами перепутаны. Логичнее сперва объявить коснтанты, потом указать тип, который может быть одиним из констант. И далее пользуешься константами, тогда ничего не напутаешь. 
`export type TGamePages = PLAY_PAGE  | RESULTS_PAGE ;`
Кроме того, раз ты их експортируешь, то лучше вынести в константы в общей папке констант и типов.

2021-04-15 21:30 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +  const [indexWordNow, setIndexWordNow] = useState<number | null>(null);
Не знаю еще как ты используешь null, но если тебе нужны индексы, которые могут начинаться с нуля или булевые значения, которые могут получиться типа null == false, то может оказаться лучше устанавливать неустановленные значения в -1. Но, может так тоже норм, главное случайно не использовать приведение типов.

2021-04-15 21:30 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +      setMultiplier(multiplier + 1);
Если "опираешься" на предыдущее значение, то лучше использовать колбек` prev => prev + 1`

2021-04-15 21:30 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +      setPreMultiplier(preMultiplier + 1);
И тут тоде лучше колбек. Иначе может конфуз произойти 
`setPreMultiplier((prev) => prev + 1);`

2021-04-15 21:30 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +    setCurrentInARow(currentInARow + 1);
колбек

2021-04-15 21:30 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +      setMaxInARow(currentInARow + 1);
колбек

2021-04-15 21:30 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +          'Sprint',
Сохранение статистики нужно оформить чуть иначе. Там есть еще проверка на то, откуда зашел пользователь в игру. Можено глянуть как сделано в имаджинариуме
![image](https://user-images.githubusercontent.com/20399054/114937269-41933d80-9e46-11eb-814c-adf22d8aaa6c.png)

2021-04-15 21:30 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +        console.log(' wronglyAnswered', wronglyAnswered);
Убери консольки

2021-04-15 21:30 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +      if (answer) {
`answer `какая то непонятная штука. Судя по использованию лучше переименовать во что-то типа `isAnswerCorrect` или ка кто так

2021-04-15 21:30 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +  }, [dispatch, group, page]);
Тут тоже не корректно. Мы слова сами не загружаем 
Используй селект
![image](https://user-images.githubusercontent.com/20399054/114938298-9d11fb00-9e47-11eb-92ca-276f4872e684.png)
Там уже будут сформированные слова для игры. Лучше всего посмотреть ПР https://github.com/Malagor/rs-lang/pull/110 там написано, что и как. И можно реализацию глянуть в имаджинариуме

2021-04-15 21:30 UTC, Malagor commented on src/modules/Sprint/components/PlayPage/PlayPage.tsx
> +  };
Что-то хочется это в одну функцию переделать и ответ в аргументе передавать булевым значением. Типа, увеличивать или нет показатели. А при вызове уже передавать `!isRightCase` или `isRightCase`

2021-04-15 21:30 UTC, Malagor commented on src/modules/Sprint/components/PlayPage/PlayPage.tsx
> +              onClick={handleRightButton}
Вот тут передавать в функцию обработчик тру или фолс в зависимости от того, что там нужно для обработки

2021-04-15 21:30 UTC, Malagor commented on src/modules/Sprint/components/PlayPage/PlayPage.tsx
> +              onClick={handleWrongButton}
И тут тоже самое, только передпавать отрицание

2021-04-15 21:30 UTC, Malagor commented on src/modules/Sprint/components/PlayPage/styled.ts
> +  }
Вот тут тоже можно было бы в одну кнопку объединить и в качестве параметра передавать что-нибудь. А потом просто проверять, если передано значение, то применять некие стили, а если нет, то дефолтные стили применять.

2021-04-16 08:39 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +        randomNumWordTranslate();
Всё, допер, у тебя тут рекурсия...

2021-04-16 08:42 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +const TIME_GAME = 60;
Поправил

2021-04-16 08:48 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +        console.log(' wronglyAnswered', wronglyAnswered);
Убрал

2021-04-16 09:32 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +  }, [dispatch, group, page]);
поправил

2021-04-16 09:33 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +      if (answer) {
поправил

2021-04-16 09:37 UTC, Malagor commented on src/modules/Sprint/components/PlayPage/PlayPage.tsx
> +  };
Поправил

2021-04-16 09:37 UTC, Malagor commented on src/modules/Sprint/components/PlayPage/PlayPage.tsx
> +              onClick={handleRightButton}
Поправил

2021-04-16 09:37 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +          'Sprint',
Статистику вынес в helper. Добавил проверку на точку входа

2021-04-16 09:38 UTC, Malagor commented on src/modules/Sprint/components/PlayPage/PlayPage.tsx
> +              onClick={handleWrongButton}
поправил

2021-04-16 09:42 UTC, Malagor commented on src/modules/Sprint/components/PlayPage/styled.ts
> +  }
Сделал одину кнопку с условием в качестве пропса

2021-04-16 09:43 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +export const RESULTS_PAGE = 'resultsPage';
Вместо этой конструкции завел стейт `isFinishGame`

2021-04-16 13:29 UTC, Malagor approved these changes

2021-04-16 14:13 UTC, closed without merging