RSL-65 main page info
Malagor/rs-lang pull request #132
Opened 2021-04-15 18:04 UTC by Malagor

CLoses: #130 
Заполнил главную страницу. Проверьте ошибки пожалуйста. Я гуглом переводил, поэтому возможны коломбуры.

2021-04-15 18:23 UTC, femiarkh requested changes

2021-04-15 18:23 UTC, femiarkh commented on src/appConstants/index.ts
> +      'I\'ve developed "Imaginarium" minigame, various common components for the minigames, and customized pagination. It was a great experience of working on an fun project as a part of a strong and
I've убери тогда, чтоб унифицированно было.

2021-04-15 18:23 UTC, femiarkh commented on src/appConstants/index.ts
> +      'Designed layout of the application, made main page and statistcs, made games results saving to the server, helped to think throw the logic of an app',
Вероятно, think through?
statistics
Определённый артикль в конце.

2021-04-15 18:59 UTC, Malagor commented on src/appConstants/index.ts
> +      'Designed layout of the application, made main page and statistcs, made games results saving to the server, helped to think throw the logic of an app',
Поправил

2021-04-15 18:59 UTC, Malagor commented on src/appConstants/index.ts
> +      'I\'ve developed "Imaginarium" minigame, various common components for the minigames, and customized pagination. It was a great experience of working on an fun project as a part of a strong and
Поправил

2021-04-16 06:50 UTC, femiarkh approved these changes

2021-04-16 08:18 UTC, Liza-Veis approved these changes

2021-04-16 08:20 UTC, merged