Rsl 04
Malagor/rs-lang pull request #16
Opened 2021-03-24 16:48 UTC by Vadim-Bykov

Сделана карточка. Добавлено озвучивание слов и предложений, смена цветов в соответствии с уровнем слжоности слов. Добавлены брэйк поинты в соответствии с макетом. Цифры со статистическими данными (красный и зеленый блоки вверху справа) и булевы значения для отображения перевода и кнопок  захардкожены в родительской компоненте WordList.
![Screenshot 2021-03-24 193303](https://user-images.githubusercontent.com/70739750/112349380-ba84f680-8cd9-11eb-9ae9-9ffc6676e293.png)

2021-03-24 18:39 UTC, femiarkh requested changes
Надо бы немного причесать файловую структуру (добавить папку components), поправить цвета плашечек угадываний-неугадываний и починить многоголосие в аудио.

2021-03-24 18:39 UTC, femiarkh commented on src/modules/TextBookPage/components/WordCard/ButtonsBlock/ButtonsBlock.tsx
> +      background: '#C4C4C4',
Серый цвет у нас добавлен в appConstants. Белый тоже есть.

2021-03-24 18:39 UTC, femiarkh commented on src/modules/TextBookPage/components/WordCard/WordCard.tsx
> +import { ButtonsBlock } from './ButtonsBlock';
У нас немного другой подход к структуре: подкпомпоненты мы складываем в специальную папочку components внутри компонента. Можешь посмотреть на примере Layout.

2021-03-24 18:39 UTC, femiarkh commented on src/modules/TextBookPage/components/WordCard/TopPart/TopPart.tsx
> +          <InfoBlock color="#fc515b">{countIntoRedBlock}</InfoBlock>
Эти цвета должны быть другими: число угадываний - цвета раздела, число ошибок - тёмно-серого цвета. Смотри обновлённый макет. Соответственно, и названия пропсов тоже следует поменять. Лучше называть их не по цвету, а по назначению.

2021-03-24 18:39 UTC, femiarkh commented on src/modules/TextBookPage/components/WordCard/TopPart/TopPart.tsx
> +    }
Неплохо бы ещё добавить логику, чтобы предыдущее проигрывание прекращалось, если пользователь повторно нажал на иконку аудио. А не то сейчас, если быстро понажимать на них, получается какафония.

2021-03-24 18:39 UTC, femiarkh commented on src/modules/TextBookPage/components/WordCard/ButtonsBlock/styled.ts
> +  @media (max-width: 860px) {
Как вариант, можно передать тему и использовать её breakpoints.

2021-03-24 18:39 UTC, femiarkh commented on src/modules/TextBookPage/components/WordCard/styled.ts
> +    /* min-height: 676px; */
Зачем этот коммент?

2021-03-24 18:39 UTC, femiarkh commented on src/modules/TextBookPage/components/WordCard/styled.ts
> +export const WordImage = styled.div<ImageUrl>`
На мой взгляд, правильнее было бы использовать тег img, а не задавать картинку бэкграундом, т.к. это - неотъемлемая часть контента, а не какой-то декоративный элемент. Но пусть будет бэкграунд.

2021-03-24 18:39 UTC, femiarkh commented on src/modules/TextBookPage/components/WordsList/WordList.tsx
> +import { LEVEL_COLORS } from '../../../../appConstants/colors';
Папка `src` служит корнем проекта. Этот путь можно заменить на `'appConstants/colors'`.

2021-03-24 18:39 UTC, femiarkh commented on tsconfig.json
> +, "src/modules/TextBookPage/components/WordCard/SentencesBlock/.tsx"  ]
Зачем эта строчка?

2021-03-24 19:56 UTC, Vadim-Bykov commented on src/modules/TextBookPage/components/WordCard/ButtonsBlock/styled.ts
> +  @media (max-width: 860px) {
Не понимаю как это сделать, если можно - оставлю пока так.

2021-03-24 20:06 UTC, Vadim-Bykov commented on src/modules/TextBookPage/components/WordCard/styled.ts
> +export const WordImage = styled.div<ImageUrl>`
Необходимо было вписать картинку в размер блока, поэтому использовал background-image: url и background-size: cover;

2021-03-24 20:10 UTC, Vadim-Bykov commented on tsconfig.json
> +, "src/modules/TextBookPage/components/WordCard/SentencesBlock/.tsx"  ]
Сам не заметил и не понял как она попала

2021-03-24 20:33 UTC, Vadim-Bykov commented on src/modules/TextBookPage/components/WordCard/ButtonsBlock/ButtonsBlock.tsx
> +      background: '#C4C4C4',
Изменение в коммите refactor: update code according to rewiew 57230c2

2021-03-24 20:33 UTC, Vadim-Bykov commented on src/modules/TextBookPage/components/WordCard/TopPart/TopPart.tsx
> +          <InfoBlock color="#fc515b">{countIntoRedBlock}</InfoBlock>
Изменение в коммите refactor: update code according to rewiew 57230c2

2021-03-24 20:34 UTC, Vadim-Bykov commented on src/modules/TextBookPage/components/WordCard/styled.ts
> +    /* min-height: 676px; */
Изменение в коммите refactor: update code according to rewiew 57230c2

2021-03-24 20:34 UTC, Vadim-Bykov commented on tsconfig.json
> +, "src/modules/TextBookPage/components/WordCard/SentencesBlock/.tsx"  ]
Изменение в коммите refactor: update code according to rewiew 57230c2

2021-03-24 20:35 UTC, Vadim-Bykov commented on src/modules/TextBookPage/components/WordsList/WordList.tsx
> +import { LEVEL_COLORS } from '../../../../appConstants/colors';
Изменение в коммите refactor: update code according to rewiew 57230c2

2021-03-24 21:00 UTC, Malagor reviewed
Отличная работа. Прям все красивенько. Подумай о переносе картинок из бека в имедж. Заодно "обкатаешь" новое свойство.

2021-03-24 21:00 UTC, Malagor commented on src/modules/TextBookPage/components/WordCard/components/SentencesBlock/SentencesBlock.tsx
> +      <Sentence dangerouslySetInnerHTML={{ __html: word.textMeaning }} />
Прикольно, даже не знал, что так можно. Молодец, что решил этот вопрос с отображением разметки.

2021-03-24 21:00 UTC, Malagor commented on src/modules/TextBookPage/components/WordCard/components/SentencesBlock/styled.ts
> +  color: #888888;
Вынеси в константу этот цвет в файл констант цветов. В раздел LAYOUT_...

2021-03-24 21:00 UTC, Malagor commented on src/modules/TextBookPage/components/WordCard/components/TopPart/TopPart.tsx
> +          onClick={onPlay}
Отлично сделал обработку озвучки. Давай немного усовершенствуем её. Сделаем возможность отменить воспроизведение. И добавим иконку "стоп" - квадратик черный. 

И если "стоп" то прерывать запись. Можно сделать локальный стейт с переменной, которую включать\выключать.

Второй момент. Сейчас можно нажать несколько карточек и они все будут воспроизводиться. Одновременно, что не очень удобно. Хотелось бы, что бы запуск очередной карточки прерывал другие воспроизведения.
Я предлагаю сделать переменные в глобальном стейте, куда заносить текущие файлы. И если нажата новая кнопочка, то перезаписывать их там  и делать воспроизведение заново. 
Заодно потренируешься в работе с "множественным" стейтом, экшенами и селекторами как в текущей "комплектации" проекта. 

Кроме того, эту фичу мы себе запишем в доп функционал, так как это будут хорошие, удобные функции.

2021-03-24 21:00 UTC, Malagor commented on src/modules/TextBookPage/components/WordCard/components/TopPart/styled.ts
> +export const InfoBlock = styled.div<{ color: string }>`
Норм решение, что бы не плодить типы.

2021-03-24 21:00 UTC, Malagor commented on src/modules/TextBookPage/components/WordCard/styled.ts
> +export const WordImage = styled.div<ImageUrl>`
У картинки есть стиль object-fit, который при указанных ширине и высоте размещает картинку cover или container. Так что может всеже перенести в img?

2021-03-24 21:03 UTC, Malagor approved these changes

2021-03-24 21:03 UTC, Malagor commented on src/modules/TextBookPage/components/WordCard/components/TopPart/TopPart.tsx
> +          <InfoBlock color={COLOR_LAYOUT_GRAY}>{errorCount}</InfoBlock>
Давай добавим сюда еще title с подсказкой, что это за значения такие.
Вот пример
![image](https://user-images.githubusercontent.com/20399054/112382897-7b689c80-8cfd-11eb-9df2-3d59926c6ec5.png)

2021-03-25 04:52 UTC, femiarkh commented on src/modules/TextBookPage/components/WordCard/ButtonsBlock/styled.ts
> +  @media (max-width: 860px) {
Можно, просто брэйкпоинты будут немного не совпадать. Может глянуть, как сейчас в пагинации. Ловится тема с помощью `useTheme()`, которая затем передаётся стилизованному компоненту. В ней лежат брейкпоинты. Не скажу, что это суперрешение, но оно хотя бы позволяет унифицировать брейкпоинты.

2021-03-25 15:11 UTC, Vadim-Bykov commented on src/modules/TextBookPage/components/WordCard/TopPart/TopPart.tsx
> +    }
Исправлено в коммите fix: solve the problem with the playing every sound from start

2021-03-25 15:12 UTC, Vadim-Bykov commented on src/modules/TextBookPage/components/WordCard/ButtonsBlock/styled.ts
> +  @media (max-width: 860px) {
Исправлено в коммите feat: add button stop for sounds

2021-03-25 15:13 UTC, Vadim-Bykov commented on src/modules/TextBookPage/components/WordCard/styled.ts
> +export const WordImage = styled.div<ImageUrl>`
Исправлено в коммите feat: add button stop for sounds

2021-03-25 15:13 UTC, Vadim-Bykov commented on src/modules/TextBookPage/components/WordCard/components/SentencesBlock/SentencesBlock.tsx
> +      <Sentence dangerouslySetInnerHTML={{ __html: word.textMeaning }} />
Спасибо.

2021-03-25 15:15 UTC, Vadim-Bykov commented on src/modules/TextBookPage/components/WordCard/components/TopPart/TopPart.tsx
> +          onClick={onPlay}
Исправлено в коммитах feat: add button stop for sounds и  fix: solve the problem with the playing every sound from start

2021-03-25 15:16 UTC, Vadim-Bykov commented on src/modules/TextBookPage/components/WordCard/components/SentencesBlock/styled.ts
> +  color: #888888;
Исправлено в коммите feat: add button stop for sounds

2021-03-25 15:17 UTC, Vadim-Bykov commented on src/modules/TextBookPage/components/WordCard/components/TopPart/styled.ts
> +export const InfoBlock = styled.div<{ color: string }>`
Спасибою

2021-03-25 15:18 UTC, Vadim-Bykov commented on src/modules/TextBookPage/components/WordCard/components/TopPart/TopPart.tsx
> +          <InfoBlock color={COLOR_LAYOUT_GRAY}>{errorCount}</InfoBlock>
Исправлено в коммите feat: add button stop for sounds

2021-03-25 16:45 UTC, Malagor approved these changes

2021-03-25 16:45 UTC, Malagor commented on src/modules/TextBookPage/components/WordCard/components/TopPart/TopPart.tsx
> +import { getSounds } from '../../../../selectors';
Сделай пути от корня. modules/TextbookPage/actions ...

2021-03-25 16:45 UTC, Malagor commented on src/modules/TextBookPage/selectors.ts
> +export const getSounds = (state: State) => state.textBookReducer.sounds;
Переименуй по аналогии через selectSound

2021-03-25 17:12 UTC, Vadim-Bykov commented on src/modules/TextBookPage/components/WordCard/components/TopPart/TopPart.tsx
> +import { getSounds } from '../../../../selectors';
Изменил в коммите refactor: rename action and change path to action and selector

2021-03-25 17:13 UTC, Vadim-Bykov commented on src/modules/TextBookPage/selectors.ts
> +export const getSounds = (state: State) => state.textBookReducer.sounds;
Переименовал refactor: rename action and change path to action and selector

2021-03-25 17:17 UTC, Malagor approved these changes

2021-03-25 17:22 UTC, femiarkh approved these changes

2021-03-25 17:29 UTC, merged