Rsl 09
Malagor/rs-lang pull request #23
Opened 2021-03-24 20:22 UTC by Andrei107Q

Close #10 

Добавлена боковая панель для переключения разделов. 
`position: sticky` не работает так как мешает  `overflow: auto`
![image](https://user-images.githubusercontent.com/58862645/112377990-6e48af00-8cf7-11eb-83ed-eb6e53b7d42e.png)

стиль по макету 
![image](https://user-images.githubusercontent.com/58862645/112378273-c7b0de00-8cf7-11eb-83c4-77ed2fe9bfe6.png)

2021-03-25 06:47 UTC, femiarkh requested changes
Разберись с различиями между `page` и `group`, сейчас эти понятия у тебя смешаны в кучу. И ещё один момент:  сейчас, если я перейду в другой раздел, он загрузится с той же страницы, на которой пользователь находился в предыдущем разделе. А неплохо бы, чтобы он загружался с 1 страницы. Если пользователь переходит по разделам, вряд ли он планирует перемещаться между, скажем, 12-ми страницами.

2021-03-25 06:47 UTC, femiarkh commented on src/modules/TextBookPage/components/WordsList/WordList.tsx
> +  changeGroupPage: Function;
Просто написать `Function` не очень полезно. Лучше указать, какие аргументы функция принимает и что возвращает. Например, в данном случае: `changeGroupPage(numberPage: number): void`.

2021-03-25 06:47 UTC, femiarkh commented on src/appConstants/index.ts
> +export const NUMBER_OF_PAGE = 6;
Слово "page" может немного запутывать. Если имеются в виду разделы учебника, лучше было бы назвать это `NUMBER_OF_SECTIONS`, `NUMBER_OF_GROUPS` или что-то типа того.

2021-03-25 06:47 UTC, femiarkh commented on src/modules/TextBookPage/components/WordsList/components/NavigationSection/NavigationSection.tsx
> +  const page = useSelector(selectPage);
Вот почему я говорю о том, что слово page может запутывать. Этим селектором ты выбираешь страницу **внутри раздела**. Это которых 30 штук, а не 6. А потом используешь её так, словно речь о разделах.

2021-03-25 06:47 UTC, femiarkh commented on src/modules/TextBookPage/components/WordsList/components/NavigationSection/NavigationSection.tsx
> +    changeGroupPage(numberPage);
Зачем тебе локальный стейт наряду с глобальным? Ты можешь его не заводить, а забирать номер раздела с помощью селектора и передавать его куда надо.

2021-03-25 06:47 UTC, femiarkh commented on src/modules/TextBookPage/components/WordsList/components/NavigationSection/components/ButtonNavigation/ButtonNavigation.tsx
> +  const activePage: boolean = pageNow === numberPage;
Вот здесь ты сравниваешь (изначально) страницу внутри раздела с номером самого раздела. Сейчас, пока раздел по умолчанию начинается с 0 страницы, это работает. Потом, когда начальная страница сможет стать отличной от 0, это сломается.

2021-03-25 10:34 UTC, Andrei107Q commented on src/appConstants/index.ts
> +export const NUMBER_OF_PAGE = 6;
переименовал в `NUMBER_OF_GROUPS`

2021-03-25 10:56 UTC, Andrei107Q commented on src/modules/TextBookPage/components/WordsList/components/NavigationSection/NavigationSection.tsx
> +  const page = useSelector(selectPage);
Хорошее замечание. я и не заметил что есть еще и страницы у раздела

2021-03-25 14:47 UTC, Andrei107Q commented on src/modules/TextBookPage/components/WordsList/WordList.tsx
> +  changeGroupPage: Function;
исправил

2021-03-25 19:57 UTC, Malagor requested changes
Сделано хорошо, но нужно чутка подправить и с обработчиком переключения поработать.

2021-03-25 19:57 UTC, Malagor commented on src/appConstants/index.ts
> +export const NUMBER_OF_GROUPS = 6;
Тогда уж COUNT_GROUPS.

2021-03-25 19:57 UTC, Malagor commented on src/components/NavigationSection/NavigationSection.tsx
> +  changeGroupPage,
Давай переименуем компонент в  GroupSelector или GroupNavigator. Хотя, лучше наверное селектор, и по смыслу и по функционалу подходит. Можно еще GroupPagination
А то `секции`, это не понятно. Особенно учитывая, что у нас тут группы.

2021-03-25 19:57 UTC, Malagor commented on src/components/NavigationSection/NavigationSection.tsx
> +          <Grid key={numberGroupPage} container justify="center">
Чем отличаются `numberGroupPage: number` и ` index: number`?

2021-03-25 19:57 UTC, Malagor commented on src/components/NavigationSection/NavigationSection.tsx
> +  );
Прикольный способ. Не знал о таком.
Я обычно пользуюсь таким
```
Array(6).fill(1).map((_, i) => i)
```
но у тебя прям совсем интересный.

2021-03-25 19:57 UTC, Malagor commented on src/components/NavigationSection/NavigationSection.tsx
> +            >
`ChangePageHandler={onChangePageHandler}`
Давай вместо проброса функции дальше сделай обработчик `onClick= ` и передадим туда номер страницы. В нашем случае это `index`
То есть пусть будет что-то вроде `onClick={() => onChangePageHandler(index) }`
Саму же функцию `onChangePageHandler(index) ` объяви здесь, не принимай её извне и там вызови dispatch. По сути перенеси то что меняет странички из TextBookPage

2021-03-25 19:57 UTC, Malagor commented on src/components/NavigationSection/NavigationSection.tsx
> +          color: `${colorText}`,
По поводу стайла.
Лучше воспользоваться создателем классов как, например, во внутренних кнопочках.
Там также принимай тему, при формированиии стилей у тебя есть брейкпоинты, и на малом брейкпоинте тебе нужно выставить контейнеру горизонтальное расположение контейнера.

Там так же тебе нужно будет подкорректировать размеры контейнера и самих кнопочек.
Самым правильным решением будет, если ты сделаешь контейнер флексовым и будешь изменять flex-direction. Второй момент - сделай все размеры относительные в %% от контейнера. Тогда ты сможешь просто вписывать контейнер в любой размер и остальные элементы под него подстроятся.

2021-03-25 19:57 UTC, Malagor commented on src/components/NavigationSection/NavigationSection.tsx
> +};
Тебе не нужна эта функция тут.
Данные о текущей странице хранятся в стейте. То есть ты в любом месте можешь воспользоваться dispatch(setPage(num)) и сохранить номер текущей страницы, а остальное все перересуется. Можешь посмотреть как сделано на TextBookPage. Вот можешь точно так же сделать. Хоть даже в самой кнопке при клике на нее.

2021-03-25 19:57 UTC, Malagor commented on src/components/NavigationSection/components/ButtonNavigation/ButtonNavigation.tsx
> +  };
Отсюда убираем

2021-03-25 19:57 UTC, Malagor commented on src/components/NavigationSection/components/ButtonNavigation/ButtonNavigation.tsx
> +  onChangePageHandler,
этого не будет

2021-03-25 19:57 UTC, Malagor commented on src/components/NavigationSection/components/ButtonNavigation/ButtonNavigation.tsx
> +      onClick={clickNumPage}
это убираем

2021-03-25 19:57 UTC, Malagor commented on src/components/NavigationSection/components/ButtonNavigation/styled.ts
> +        fontSize: '18px',
сделай размеры относительными. Что бы адаптировалось под любые экраны. Ну, или проверь как оно смотриться везде в том числе с выдвинутым меню

2021-03-25 19:57 UTC, Malagor commented on src/components/NavigationSection/components/ButtonNavigation/styled.ts
> +      color: COLOR_LAYOUT_BACKGROUND,
Та же ситуация, что и выше

2021-03-25 20:12 UTC, Malagor commented on src/components/NavigationSection/NavigationSection.tsx
> +            >
Еще момент. Внутри функции установщика страниц нужно вызвать функцию сохранения группы в локалсторедж. Для этого нужно в файле LocStore который лежит в services создать функции по сохраннению и загрузке номера группы из \в локалсторедж.
Сейчас еще нет этого файла, но как только ты обновишь дев и смержишь сюда, то он появиться. 
И вот внутри `onChangePageHandler` тебе кроме диспатча нужно еще с в локал сохранять.

Далее, в компоненте `App` загрузи эти данные из локалстореджа и сохрани в стейт. По аналогии. Прям в этот useEffect и пихай после остальных диспатчей.
![image](https://user-images.githubusercontent.com/20399054/112537085-4fadeb00-8dbf-11eb-95ab-e7e3d3de715d.png)

Создай также метод удаления ключа из локалстореджа. Но пока нигде не используй, пусть просто будет.

2021-03-26 10:07 UTC, Andrei107Q commented on src/appConstants/index.ts
> +export const NUMBER_OF_GROUPS = 6;
+

2021-03-26 11:51 UTC, Andrei107Q commented on src/components/NavigationSection/NavigationSection.tsx
> +};
да, действительно так как-то лучше и кодам меньше

2021-03-26 13:26 UTC, Andrei107Q commented on src/components/NavigationSection/NavigationSection.tsx
> +  changeGroupPage,
Переименовал

2021-03-26 15:55 UTC, Andrei107Q commented on src/components/NavigationSection/NavigationSection.tsx
> +          <Grid key={numberGroupPage} container justify="center">
убрал

2021-03-26 19:58 UTC, Andrei107Q commented on src/components/NavigationSection/NavigationSection.tsx
> +            >
готово

2021-03-27 09:20 UTC, Andrei107Q commented on src/components/GroupSelector/GroupSelector.tsx
> +            </Grid>
44,45 строка. насколько адекватно называть использовать одинаковые названия пропса и функции передаваемой в нем, или все же переименовать?

2021-03-27 09:23 UTC, Andrei107Q commented on src/components/GroupSelector/components/ButtonGroupSelector/styled.ts
> +  },
размеры решил оставить статическими. т.к. тяжело соблюдать динамичные размеры когда внутри отрисовываются круги. нужно учитывать размеры оберток. решил не заниматься лишним геморроем. размеры по макету.

2021-03-27 09:37 UTC, Andrei107Q commented on src/services/localStorage.ts
> +};
тут немного оптимизировал. но не получилось сделать методом класса. 
![image](https://user-images.githubusercontent.com/58862645/112716722-21ccc180-8ef9-11eb-8a64-424645c173b5.png)

2021-03-27 13:52 UTC, femiarkh approved these changes

2021-03-27 13:52 UTC, femiarkh commented on src/components/GroupSelector/GroupSelector.tsx
> +            </Grid>
Хороший вопрос. В принципе, ничего неадекватного тут нет, но я бы немного разграничил названия, чтобы было проще понять, что происходит. Ту функцию, что ты вызываешь в колбэке я бы назвал просто `changeGroup`, потому что именно этим она и занимается: принимает на вход номер группы и устанавливает соответствующую группу. А сам пропс вполне уместно назвать хэндлером, потому что он вызывается при клике по соответвующей кнопке.

2021-03-27 13:56 UTC, femiarkh commented on src/components/GroupSelector/GroupSelector.tsx
> +            </Grid>
Хороший вопрос. Я бы немного разграничил названия, чтобы было проще понять, что происходит. Например, функцию, которую ты вызываешь в колбэке (которая задаётся на 19 строчке) я бы назвал просто `changeGroup`, потому что именно этим она и занимается: принимает на вход номер группы и устанавливает соответствующую группу. Ну а сам пропс вполне уместно назвать хэндлером, ведь он срабатывает при клике по соответствующей кнопке.

2021-03-27 19:21 UTC, Liza-Veis commented on src/components/GroupSelector/components/ButtonGroupSelector/styled.ts
> +}));
Может заменить это все на что-нибудь такое 
![image](https://user-images.githubusercontent.com/64521658/112731587-ec4bc680-8f40-11eb-9bff-6ce4bdcadb11.png)
Это сократит код, эффекты будут не такие грубые и не будет дергаться панель при выборе активного элемента, только нужно будет еще в paperWrapper из styled для GroupSelector задать падинг в 5px, так как уменьшится ширина блока

2021-03-29 13:24 UTC, Liza-Veis commented on src/components/GroupSelector/styled.ts
> +  paperWrapper: {
Добавь тут падинг в 5px чтобы не так прижато было

2021-03-29 13:25 UTC, Liza-Veis commented on src/components/GroupSelector/styled.ts
> +    },
Добавь тут падинг 5px, чтобы не так прижато было

2021-03-29 20:30 UTC, Andrei107Q commented on src/components/GroupSelector/components/ButtonGroupSelector/styled.ts
> +}));
да, круто. так и сделал

2021-03-30 10:14 UTC, Andrei107Q commented on src/components/GroupSelector/styled.ts
> +    },
добавил 
![image](https://user-images.githubusercontent.com/58862645/112973275-d06f3d00-9159-11eb-9cdf-bde5015c3e8c.png)

2021-03-30 12:34 UTC, Malagor requested changes
Похоже я не отправил предыдущие правки... Вот отправляю. Кроме того влей сюда мои изменения из RSL 09-2 ветки, я там поправил адаптив

2021-03-30 12:34 UTC, Malagor commented on src/components/GroupSelector/GroupSelector.tsx
> +                activePage={numberGroupPage === groupPageNow}
activePage переменуй в isActive.
Все булевые переменные именуй через isSmth или hasSmth, то есть либо есть быть что-то, либо иметь что-то.
Твоя переменная ожидает номер активной страницы.

2021-03-30 12:34 UTC, Malagor commented on src/components/GroupSelector/GroupSelector.tsx
> +            </Grid>
Давай тут чуть подправим следующим образом:
![image](https://user-images.githubusercontent.com/20399054/112721945-c100b180-8f17-11eb-9950-63d2c32c1ae9.png)

А внутри перепишем вот так 
![image](https://user-images.githubusercontent.com/20399054/112721963-db3a8f80-8f17-11eb-97a6-2008c1e72920.png)

И сюда же перенесем обработчик. с диспатчами и записью в локалсторедж

2021-03-30 12:34 UTC, Malagor commented on src/components/GroupSelector/GroupSelector.tsx
> +                color={LEVEL_COLORS[numberGroupPage]}
У тебя есть выше переменная colorText. используй ее тогда и тут

2021-03-30 12:34 UTC, Malagor commented on src/components/GroupSelector/GroupSelector.tsx
> +  const groupPageNow = useSelector(selectGroup);
Тут переименуй просто в group. Не усложняй. У тебя тут других подобных переменный нет, а page и group мы используем тут повсеместно

2021-03-30 12:34 UTC, Malagor commented on src/components/GroupSelector/GroupSelector.tsx
> +  const onChangeGroupPageHandler = (numberGroupPage: number) => {
Тоже удали слово Page из описания. У нас есть группы, есть страницы. Страницы групп и группы Страниц это непонятно что такое. И пожалуй удали слово `on` в начале. `on `это событие, `handler`  обработчик.
Пусть будет типа `changeGroupHandler`

2021-03-30 12:34 UTC, Malagor commented on src/components/GroupSelector/components/ButtonGroupSelector/ButtonGroupSelector.tsx
> +    </Fab>
Перенеси сюда обработчк и передавай сюда просто номер группы. Я выше скриншот прилупасил

2021-03-30 12:34 UTC, Malagor commented on src/components/GroupSelector/components/ButtonGroupSelector/styled.ts
> +  },
Ладно, пока оставь, Но поправь выравнивание. Для эжтого нужно у контейнера сделать флекс и выравнять элементы по центру.
И нужно избавиться от этого серого цвета. Его вообще не должно быть. А на мобилках он еще и не убирается 
![image](https://user-images.githubusercontent.com/20399054/112722646-cfe96300-8f1b-11eb-86cf-8670a5939743.png)

2021-03-30 12:34 UTC, Malagor commented on src/modules/TextBookPage/styled.ts
> +      flexDirection: 'column-reverse',
Прикольно.

2021-03-30 12:34 UTC, Malagor commented on src/services/localStorage.ts
> +};
Просто статические методы не могут обращаться к this. Они вызываются по имени класса, а не из экземпляра класса. 
Норм оптимизировал, только сделай название короче. Мы тут внутри работает и класс у нас вполне понятный, так что можно переименовать функцию в getData и всё. И читать будет проще и писсать короче.

2021-03-30 12:34 UTC, Malagor commented on src/components/GroupSelector/components/ButtonGroupSelector/styled.ts
> +  COLOR_LAYOUT_GRAY,
Ты не все константы используешь, удали лишние

2021-03-31 11:44 UTC, Andrei107Q commented on src/components/GroupSelector/GroupSelector.tsx
> +  const groupPageNow = useSelector(selectGroup);
![image](https://user-images.githubusercontent.com/58862645/113139315-9ec8a580-922f-11eb-85d0-6a11166c8046.png)

2021-03-31 11:50 UTC, Andrei107Q commented on src/components/GroupSelector/GroupSelector.tsx
> +                activePage={numberGroupPage === groupPageNow}
готово.

2021-03-31 11:56 UTC, Andrei107Q commented on src/components/GroupSelector/GroupSelector.tsx
> +                color={LEVEL_COLORS[numberGroupPage]}
Тут что-то не то. Я не могу тут использовать `const colorText = LEVEL_COLORS[groupPageNow];` т.к. я внутри `map` и тут мне нужен цвет для каждой кнопки, а ` colorText` в данном случае это константа для цвета текущей станицы.

2021-03-31 12:04 UTC, Andrei107Q commented on src/components/GroupSelector/components/ButtonGroupSelector/ButtonGroupSelector.tsx
> +    </Fab>
не совсем понял, что нужно сделать. `{children}` получаю тут, а передаю номер страницы, зачем мне тут еще дополнительную логику делать? 
если дело в `onClick={() => onChangeGroupPageHandler()}` чем плохо просто его тут вызвать?
если сюда передавать функцию и вызывать ее тут. нужно прокидывать дополнительнономер страницы. и дописывать еще и обрабтчик .

2021-03-31 12:05 UTC, Andrei107Q commented on src/components/GroupSelector/components/ButtonGroupSelector/styled.ts
> +  COLOR_LAYOUT_GRAY,
![image](https://user-images.githubusercontent.com/58862645/113141532-7d1ced80-9232-11eb-8619-9c62c524e4d0.png)
готово

2021-03-31 12:10 UTC, Andrei107Q commented on src/services/localStorage.ts
> +};
Сделал. Просто в прошлый раз были замечания по поводу нечеткого именования, в этот раз решил более подробно именовать.

2021-03-31 12:14 UTC, Andrei107Q commented on src/components/GroupSelector/components/ButtonGroupSelector/styled.ts
> +  },
это наверное с другой ветки. сейчас все вот так и цвета серого нет. все по фэншую )
![image](https://user-images.githubusercontent.com/58862645/113142543-aee28400-9233-11eb-81f0-85159f9a33b3.png)
 про центрирование не совсем понял. если так как на скрине это ок или нет ?

2021-03-31 12:47 UTC, Andrei107Q commented on src/components/GroupSelector/GroupSelector.tsx
> +  const onChangeGroupPageHandler = (numberGroupPage: number) => {
удалил

2021-03-31 14:27 UTC, Andrei-Red commented on src/components/GroupSelector/styled.ts
> +    },
тут почему-то при 100%  появляется прокрутка. `width: '98%',`

2021-03-31 14:30 UTC, Andrei107Q commented on src/modules/TextBookPage/TextBookPage.tsx
> +      </Grid>
добавил на `sm={2}` и `sm={10}` т.к. сильно ужимается и появляется полоса прокрутки.

2021-04-01 20:03 UTC, merged