Rsl 17 nav game
Malagor/rs-lang pull request #39
Opened 2021-03-26 17:22 UTC by Vadim-Bykov

Сделан блок навигации по играм. Добавлены роуты в компонент App. При клике по ссылке происходит переход на страницу соответствующей игры.
![image](https://user-images.githubusercontent.com/70739750/112669482-d373e000-8e70-11eb-9b5a-506db53a087b.png)

![image](https://user-images.githubusercontent.com/70739750/112669568-ee465480-8e70-11eb-8d21-1ea042dd8260.png)

2021-03-26 18:40 UTC, Malagor requested changes
Вообще хорошо, но давай приведем в порядок немного

2021-03-26 18:40 UTC, Malagor commented on src/components/App/App.tsx
> +import { OwnGame } from 'modules/OwnGame';
Экспортируй их modules. Там есть import.ts

2021-03-26 18:40 UTC, Malagor commented on src/components/App/App.tsx
>          <Route path="/dictionary" component={DictionaryPage} />
Напиши адреса в кебаб типе audio-chalenge, our-game

2021-03-26 18:40 UTC, Malagor commented on src/components/NavGame/NavGame.tsx
> +import OWN_GAME_ICON from 'assets/icons/ownGame.png';
Ты же в константы выносил эти импорты. Так оттуда и забирай тогда.
Или из констант убирай. Но логичней все же там оставить. Если возникают сложности с реэкспортом, можешь попробовать экспортировать из констант их по отдельности, а не объектом, вдруг там какой конфликт, что есть и так и так.

2021-03-26 18:40 UTC, Malagor commented on src/components/NavGame/NavGame.tsx
> +      </Flex>
Тэкс, это кто ж так при живых то флексах делает? Почему две обертки? Что медиазапросы и width 25%-50% запретили? Не гоже так делать. Все должны лежать в одном контейнере. 

Второй момент... Было бы просто замечательно вынести все игры в константы в которой создать массив объектов типа {link, name, image} и тут размапить одной строкой.

2021-03-26 18:40 UTC, Malagor commented on src/components/NavGame/NavGame.tsx
> +import { GameItem } from './components/GameItem';
import { GameItem } from './components/GameItem';

сделай в папке компонентов index и оттуда реэкспортируй подкомпоненты, что бы максимальный путь был ./components

2021-03-26 18:40 UTC, Malagor commented on src/modules/AudioChallenge/AudioChallenge.tsx
> +  </Container>
Добавь сюда хук для изменения тайтла страницы. Посмотри как на других сделано

2021-03-26 18:40 UTC, Malagor commented on src/modules/AudioChallenge/AudioChallenge.tsx
> +  </Container>
И для других страниц игр тоже сделай

2021-03-26 18:40 UTC, Malagor commented on src/modules/DictionaryPage/DictionaryPage.tsx
> +import { NavGame } from 'components/NavGame';
Поправь импорт, должен быть из components

2021-03-26 18:40 UTC, Malagor commented on src/modules/OwnGame/OwnGame.tsx
> +    <Paper>OwnGame</Paper>
Добавь заголовок

2021-03-26 18:40 UTC, Malagor commented on src/modules/Savannah/Savannah.tsx
> +    <Paper>Savannah</Paper>
Добавь заголовок

2021-03-26 18:40 UTC, Malagor commented on src/modules/Sprint/Sprint.tsx
> +  <Container>
Добавь заголовок

2021-03-26 18:40 UTC, Malagor commented on src/modules/TextBookPage/TextBookPage.tsx
> +import { NavGame } from 'components/NavGame';
Поправь импорт

2021-03-26 18:40 UTC, Malagor commented on src/components/NavGame/components/GameItem/styled.ts
> +export const GameName = styled.div``;
А чего пустой?

2021-03-26 18:40 UTC, Malagor commented on src/components/NavGame/components/GameItem/styled.ts
> +  margin-right: ${({ lastItem }) => (lastItem ? '0px' : '16px')};
Есть волшебное свойство `gap`, используй его. Оно добавляет промежутки между флексэлементами

2021-03-26 18:40 UTC, Malagor commented on src/modules/TextBookPage/components/WordsList/WordList.tsx
> +import { NavGame } from 'components/NavGame';
Поправь импорт

2021-03-26 18:58 UTC, Vadim-Bykov commented on src/components/NavGame/NavGame.tsx
> +import OWN_GAME_ICON from 'assets/icons/ownGame.png';
Переделал. Так и было по плану (видимо отвлекали не раз, так я и нагов....ил).

2021-03-26 19:06 UTC, Vadim-Bykov commented on src/components/NavGame/NavGame.tsx
> +import { GameItem } from './components/GameItem';
Реэкспортировал

2021-03-27 05:02 UTC, femiarkh commented on src/components/NavGame/components/GameItem/styled.ts
> +  margin-right: ${({ lastItem }) => (lastItem ? '0px' : '16px')};
Gap во флексе имеет [плохую поддержку](https://caniuse.com/?search=gap). Мы, конечно, на хром ориентируемся, но это тоже стоит учитывать.

2021-03-27 05:39 UTC, Vadim-Bykov commented on src/components/App/App.tsx
> +import { OwnGame } from 'modules/OwnGame';
Перенес экспорты в modules/Index.ts и оттуда забираю их в App

2021-03-27 07:17 UTC, Vadim-Bykov commented on src/modules/TextBookPage/TextBookPage.tsx
> +import { NavGame } from 'components/NavGame';
Сделал импорт из 'components'

2021-03-27 07:22 UTC, Vadim-Bykov commented on src/components/NavGame/components/GameItem/styled.ts
> +export const GameName = styled.div``;
Стилей у него своих нет. Убрал const GameName = styled.div`` и в компонете GameIten вместо него просто добавил тег div

2021-03-27 07:39 UTC, Vadim-Bykov commented on src/components/NavGame/components/GameItem/styled.ts
> +  margin-right: ${({ lastItem }) => (lastItem ? '0px' : '16px')};
Убрал margin-right: ${({ lastItem }) => (lastItem ? '0px' : '16px')};
Добавил родителю (NavContainer) margin: 0px -8px; и его ребенку (ссылка 'a') padding: 0px 8px;. Все работает без тернарного выражения и передачи props, а так же без gap.

2021-03-27 07:47 UTC, Vadim-Bykov commented on src/modules/TextBookPage/components/WordsList/WordList.tsx
> +import { NavGame } from 'components/NavGame';
Поправил import { NavGame } from 'components';

2021-03-27 09:26 UTC, Vadim-Bykov commented on src/components/App/App.tsx
>          <Route path="/dictionary" component={DictionaryPage} />
Исправил в Route и NavLink

2021-03-27 09:27 UTC, Vadim-Bykov commented on src/components/NavGame/NavGame.tsx
> +      </Flex>
Завернул все в один контейнер и размапил внутри.

2021-03-27 09:36 UTC, Vadim-Bykov commented on src/modules/Sprint/Sprint.tsx
> +  <Container>
Добавил заголовки для страниц игр

2021-03-27 12:00 UTC, Andrei107Q commented on src/appConstants/games.ts
> +];
мне еще нужен тут будет цвет кнопки и описание. Или я сам добавлю потом.

2021-03-27 12:03 UTC, Andrei107Q approved these changes

2021-03-27 14:15 UTC, femiarkh approved these changes
Поправь импорт в `DictionaryPage`, строка `5`.

2021-03-28 07:36 UTC, Malagor reviewed
Норм, подкорректируй комменты и можно мержить

2021-03-28 07:36 UTC, Malagor commented on src/appConstants/games.ts
> +];
@Andrei107Q Так ты потом когда вольешься просто добавь сюда дополнительные поля.

2021-03-28 07:36 UTC, Malagor commented on src/components/index.ts
> +export { NavGame } from './NavGame';
Сохрани этот файл перед коммитом. Будет выскакивать автоисправление и добавлять строку внизу

2021-03-28 07:37 UTC, Malagor approved these changes

2021-03-28 07:47 UTC, Malagor reviewed
Нашел еще один файл для пересохранения. Проверь коменты в общем.

2021-03-28 07:47 UTC, Malagor commented on src/components/NavGame/components/index.ts
> +export { GameItem } from './GameItem';
Тут тоже сохрани файл перед коммитом

2021-03-28 08:53 UTC, merged