RSL-16 create layout game page 🎯 feat
Malagor/rs-lang pull request #47
Opened 2021-03-27 20:53 UTC by Andrei107Q

closes #26 

Создал станицу для игр 
роутинги прокинул через нажатие кнопки с помощью `useHistory()` 
дизайн по макету, брекпоинты material.ui
![image](https://user-images.githubusercontent.com/58862645/112734497-288a2180-8f57-11eb-8d4f-12fb4fe9dcdc.png)
для перехода на мобильный вариант 600px возможно маловато будет т.к сильно ужимается карточка.
![image](https://user-images.githubusercontent.com/58862645/112734532-743ccb00-8f57-11eb-9c45-9a8b95bd9ad3.png)

2021-03-28 12:13 UTC, Malagor requested changes
Приведи в соответствие с дизайном.

2021-03-28 12:13 UTC, Malagor commented on src/modules/GamesPage/components/GemeCard/index.ts
> +export { GameCard } from './GameCard';
Проверь имя папки gAme, у тебя gEme

2021-03-28 12:13 UTC, Malagor commented on src/modules/GamesPage/components/GemeCard/styled.ts
> +      borderColor: `${props.colorButton} 0.1`,
Возможно нужно добавить `lighten()`?

2021-03-28 12:13 UTC, Malagor commented on src/modules/GamesPage/components/GemeCard/styled.ts
> +      borderColor: `${props.colorButton} 0.5`,
Тут тоже `lighten(${props.colorButton} 0.5),`
Я подсвечивал сложные карточки в текстБуке, можно там глянуть как правильно записать

2021-03-28 12:13 UTC, Malagor commented on src/modules/GamesPage/components/GemeCard/styled.ts
> +  },
Пиведи в соответствие с дизайном

2021-03-28 12:13 UTC, Malagor commented on src/modules/GamesPage/components/GemeCard/styled.ts
> +  },
На мобилках карточка не влезет в экран. Так как задан жесткий width. Она не уменьшиться.

2021-03-28 12:13 UTC, Malagor commented on src/modules/GamesPage/components/GemeCard/styled.ts
> +      boxShadow: '0 0 0 0.2rem rgba(0,123,255,.5)',
Что за цвет?

2021-03-28 12:13 UTC, Malagor commented on src/modules/GamesPage/GamesPage.tsx
> +          />
Тfкие штуки лучше сразу деструктурировать const {name, img ...} = gameData, аккуратней смотрится.

2021-03-28 17:22 UTC, Liza-Veis commented on src/modules/GamesPage/components/GemeCard/styled.ts
> +      borderColor: `${props.colorButton} 0.1`,
Да и в значения 0.2 передать, а то 0.1 не сильно заметно

2021-03-28 18:15 UTC, femiarkh requested changes

2021-03-28 18:15 UTC, femiarkh commented on src/modules/GamesPage/components/GameCard/GameCard.tsx
> +      <Card className={`${classes.cardWrapper} ${classes.wrapper}`}>
Тень карточки не совпадает с макетом. На макете тень гораздо мягче и нижний край так не подчёркнут. Либо поиграйся с `elevation`, либо вручную пропиши `box-shadow` в стилях.

2021-03-28 18:15 UTC, femiarkh commented on src/modules/GamesPage/components/GameCard/styled.ts
> +    MinHeight: '308px',
А чего с большой буквы?

2021-03-28 19:46 UTC, Andrei107Q commented on src/modules/GamesPage/components/GameCard/GameCard.tsx
> +      <Card className={`${classes.cardWrapper} ${classes.wrapper}`}>
я в фигме не  нашел где тени у карточек прописываются

2021-03-28 19:47 UTC, Andrei107Q commented on src/modules/GamesPage/components/GameCard/styled.ts
> +    MinHeight: '308px',
точно. исправляю

2021-03-28 19:49 UTC, femiarkh commented on src/modules/GamesPage/components/GameCard/GameCard.tsx
> +      <Card className={`${classes.cardWrapper} ${classes.wrapper}`}>
![Screenshot_6](https://user-images.githubusercontent.com/55946100/112765845-cd6c3380-9017-11eb-8057-1157a65f5117.jpg)

2021-03-29 06:41 UTC, Vadim-Bykov commented on src/modules/GamesPage/components/GameCard/styled.ts
> +  },
Посмотри что можно сделать со стилями. AudioChallenge съезжает и прокрутка горизонтальная при открытом меню.
![image](https://user-images.githubusercontent.com/70739750/112796449-a7c04800-9072-11eb-8ddb-e0189908138e.png)

2021-03-29 06:45 UTC, Vadim-Bykov requested changes
Посмотри что можно сделать со стилями . При сужении экрана от 700px у AudioChallenge название игры съезжает и прокрутка горизонтальная при открытом меню.

2021-03-30 10:08 UTC, Andrei107Q commented on src/modules/GamesPage/components/GameCard/styled.ts
> +  },
Проверь пожалуйста еще раз. возможно ты не перезагрузил страницу когда менял размеры. все должно работать вот так 
![image](https://user-images.githubusercontent.com/58862645/112970827-4aea8d80-9157-11eb-821d-b5a6caaa48f9.png)
![image](https://user-images.githubusercontent.com/58862645/112970897-5938a980-9157-11eb-84a9-da7b85fe6c73.png)

такой эффект что на твоем скрине происходит если ты просто стягиваешь экран. тогда боковое меню не может перестроиться под мобильный вариант. 
и получается такое 
![image](https://user-images.githubusercontent.com/58862645/112972398-e6303280-9158-11eb-97f9-43502033b051.png)
но в реальной жизни все будет выглядеть как на первом скрине.

2021-03-31 08:47 UTC, Malagor requested changes
Почти завершили. Давай еще расстояния между карточек поправим с сдедлаем их независимыси от количества контента

2021-03-31 08:47 UTC, Malagor commented on src/modules/GamesPage/components/GameCard/GameCard.tsx
> +      <Card className={`${classes.cardWrapper} ${classes.wrapper}`}>
Верхний Grid нужно убрать вовсе.
А у Card поправить маржины на 20px 20px.
Тогда станет как в макете.

2021-03-31 08:47 UTC, Malagor commented on src/modules/GamesPage/components/GameCard/GameCard.tsx
> +          <Typography className={classes.description}>{description}</Typography>
Если дескрипшен будет не одинаковым, то поедедт вертска внтури карточки. Сделай внутри карточки гридконтейнер а для кнопки задай стиль marginTop: 'auto'.
Это прижмет кнопку к низу а весь контент подвинет наверх. Тогда будет смотреться аккуратно

2021-03-31 08:47 UTC, Malagor commented on src/modules/GamesPage/components/GameCard/styled.ts
> +    margin: '39px 30px',
Вот тут сделай маржины 20-20

2021-03-31 09:31 UTC, Vadim-Bykov approved these changes

2021-03-31 15:37 UTC, Andrei107Q commented on src/modules/GamesPage/components/GameCard/GameCard.tsx
> +      <Card className={`${classes.cardWrapper} ${classes.wrapper}`}>
Исправил.

2021-03-31 16:04 UTC, Andrei107Q commented on src/modules/GamesPage/components/GameCard/styled.ts
> +    margin: '39px 30px',
окей. по макету были разные отступы. сдела всегда одинаковые `20px`
![image](https://user-images.githubusercontent.com/58862645/113175121-c467a600-9253-11eb-9187-c816731df278.png)
![image](https://user-images.githubusercontent.com/58862645/113175246-e6612880-9253-11eb-975f-87b591f11474.png)

2021-03-31 16:27 UTC, Andrei107Q commented on src/modules/GamesPage/components/GameCard/GameCard.tsx
> +          <Typography className={classes.description}>{description}</Typography>
![image](https://user-images.githubusercontent.com/58862645/113178220-09d9a280-9257-11eb-938b-0f28cf0fa804.png)
решил.

2021-04-01 03:04 UTC, Liza-Veis approved these changes

2021-04-01 08:31 UTC, femiarkh approved these changes

2021-04-01 13:54 UTC, Malagor reviewed
Есть небольшая коменташка, а так все отлично.

2021-04-01 13:54 UTC, Malagor commented on src/modules/GamesPage/components/GameCard/GameCard.tsx
> +      <Grid container item xs={12} className={classes.wrapper}>
Тут `item `не нужен, да и `xs `можно не указывать, контейнер на 100% ширины пытается разместиться

2021-04-01 13:55 UTC, Malagor approved these changes

2021-04-01 15:23 UTC, merged