Rsl 30 dictionary
Malagor/rs-lang pull request #62
Opened 2021-03-31 16:30 UTC by Vadim-Bykov

Сделал страницу словаря с разделами. В раздел Learning words попадают слова юзера, т.к. нет пока подходящего запроса на API, в раздел Difficult words - сложные слова,  в раздел Deleted words - удаленные слова. При переключении по разделам остаемся в той же группе слов, цвет маркера меняется согласно группы. Компоненты WordList и WordCard вынесены отдельно в src/components, т.к. используются в двух компонентах.
![image](https://user-images.githubusercontent.com/70739750/113178560-6210a480-9257-11eb-8a95-169ce0be7953.png)

2021-04-01 07:59 UTC, femiarkh reviewed
Сейчас меня больше всего смущает то, что при каждом клике по кнопке на карточке страница исчезает, а потом открывается с самого верха. Получается, после любой операции над карточкой нужно снова скроллить к тому же месту. Надо что-то с этим сделать, а то неудобно. И хорошо ещё бы, если бы лоадер закрывал не весь экран, а только область с обрабатываемой карточкой.

2021-04-01 07:59 UTC, femiarkh commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
> +    if (wordSection === 'usual')
Эти слова ('usual', 'difficult', 'deleted') неплохо бы вынести в константы.

2021-04-01 07:59 UTC, femiarkh commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
> +              handlerAddWordToList(userId, wordId, 'hard', group, page)
Вообще, функции принято называть глаголами. Т.е. не 'handler', а 'handle'. Или, если очень хочется назвать хэндлером, то само слово лучше поставить в конце: `addWordToListHandler`.

2021-04-01 07:59 UTC, femiarkh commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
>    showBtnRestore: boolean;
А зачем нужны отдельные флажки для показа кнопок удаления/добавления в сложные и восстановления? Это будут разные настройки у пользователя?

2021-04-01 07:59 UTC, femiarkh commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
> +              handlerAddWordToList(userId, wordId, 'easy', group, page)
Слова 'easy' и 'hard' тоже лучше записать в константы. Слово 'easy' вообще сбивает с толку и не отражает сущность явления. Как выяснилось, в "удалённые" должны попадать слова, которые пользователь по каким-то причинам не хочет учить. И не обязательно причина состоит в том, что слово лёгкое.

2021-04-01 07:59 UTC, femiarkh commented on src/components/WordCard/styled.ts
> +import { COLOR_LAYOUT_BACKGROUND } from '../../appConstants/colors';
Точки можно убрать.

2021-04-01 07:59 UTC, femiarkh commented on src/components/WordsList/WordList.tsx
> +  checkedDifficulty: string;
Наверное, не любая строка, а только 'easy' или 'hard'? Тогда лучше так и указать.

2021-04-01 07:59 UTC, femiarkh commented on src/components/WordsList/WordList.tsx
> +    if (i === 20) return acc;
Число нужно вынести в константу.

2021-04-01 07:59 UTC, femiarkh commented on src/components/WordsList/WordList.tsx
> +  );
Почему у них у всех стоит `|| 1`? Это ведь статистика правильных и неправильных ответов, так? То есть по умолчанию у каждой карточки будет 1 верный и неверный ответ?

2021-04-01 07:59 UTC, femiarkh commented on src/helpers/dictionaryHelpers.ts
> +  }
Можно инициализировать с 0 и убрать блок else, чуть короче будет.

2021-04-01 07:59 UTC, femiarkh commented on src/modules/DictionaryPage/DictionaryPage.tsx
> +    const nextGroup = group === 5 ? 5 : group + 1;
Число групп тоже в константы.

2021-04-01 07:59 UTC, femiarkh commented on src/modules/DictionaryPage/DictionaryPage.tsx
> +  };
Три практически одинаковых хэндлера, можно было написать один, меняющий пару слов в зависимости от параметров.

2021-04-01 07:59 UTC, femiarkh commented on src/modules/DictionaryPage/components/Sections/styled.ts
> +  background-color: ${({ colorGroup }) => colorGroup || '#c4c4c4'};
Этот цвет есть в константах.

2021-04-01 07:59 UTC, femiarkh commented on src/modules/DictionaryPage/components/StatisticModal/styled.ts
> +// `;
Что это за закоменченная часть?

2021-04-01 12:13 UTC, femiarkh commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
>    showBtnRestore: boolean;
Или это заготовка для разных страниц? Словарь/учебник?

2021-04-01 14:19 UTC, Malagor commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
> +              handlerAddWordToList(userId, wordId, 'easy', group, page)
Изи и хард забиты в тип принимаемого пропса. Другие просто не введешь. МОжнр было енумку сделать, может еще проще было бы, но ка кто так уже пошло.
Изначально я думал, что удаленные, это типа, уже легкие, а потом всплыло, что это не совсем легкие.

2021-04-01 14:23 UTC, femiarkh commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
> +              handlerAddWordToList(userId, wordId, 'easy', group, page)
Дело не только в том, введёшь или нет. Если бы там было написано `DELETED`, было бы сразу ясно, о чём речь. А так приходится вспоминать, что это за лёгкие слова такие.

2021-04-01 17:37 UTC, Vadim-Bykov commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
> +    if (wordSection === 'usual')
Сделал чтобы при клике по кнопке на карточке страница не исчезает. Эти слова ('usual', 'difficult', 'deleted') вынес в константы.

2021-04-01 17:40 UTC, Vadim-Bykov commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
> +              handlerAddWordToList(userId, wordId, 'hard', group, page)
Переименовал в handleAddWordToList.

2021-04-01 17:46 UTC, Vadim-Bykov commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
>    showBtnRestore: boolean;
![image](https://user-images.githubusercontent.com/70739750/113333448-1cbda700-932b-11eb-898f-bf2f47018ac6.png)
Сейчас кнопки показываются в зависимости от того на какую секцию слов мы перекличились

2021-04-01 17:56 UTC, Vadim-Bykov commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
> +              handlerAddWordToList(userId, wordId, 'easy', group, page)
Занес везде, где использовались 'easy' и 'hard' в константы HARD_DIFFICULTY и EASY_DIFFICULTY

2021-04-01 17:57 UTC, Vadim-Bykov commented on src/components/WordCard/styled.ts
> +import { COLOR_LAYOUT_BACKGROUND } from '../../appConstants/colors';
Убрал.

2021-04-01 17:59 UTC, Vadim-Bykov commented on src/helpers/dictionaryHelpers.ts
> +  }
Переделал на укороченный вариант.

2021-04-01 18:01 UTC, Vadim-Bykov commented on src/modules/DictionaryPage/DictionaryPage.tsx
> +    const nextGroup = group === 5 ? 5 : group + 1;
Эти числа и кнопки уберутся после добавления этого переключателя
![image](https://user-images.githubusercontent.com/70739750/113335312-6dce9a80-932d-11eb-9c1c-27fa4867f6cd.png)

2021-04-01 18:35 UTC, Vadim-Bykov commented on src/modules/DictionaryPage/DictionaryPage.tsx
> +  };
Можно, но получается не очень хорошо, даже хуже, т.к. я в Sections их передаю массивом и там потом размапливаю по индексу. Вообщем пробовал, но некрасиво получилось в Section

2021-04-01 18:37 UTC, Vadim-Bykov commented on src/modules/DictionaryPage/components/Sections/styled.ts
> +  background-color: ${({ colorGroup }) => colorGroup || '#c4c4c4'};
Заменил на константу.

2021-04-01 18:38 UTC, Vadim-Bykov commented on src/modules/DictionaryPage/components/StatisticModal/styled.ts
> +// `;
Был еще процесс доработки, удрал.

2021-04-02 06:14 UTC, femiarkh commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
> +              handlerAddWordToList(userId, wordId, 'easy', group, page)
Так ведь не Easy же. 'easy' - это не что иное, как удалённые слова, так? Почему бы тогда не назвать их `DELETED`?

2021-04-02 15:00 UTC, Vadim-Bykov commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
> +              handlerAddWordToList(userId, wordId, 'easy', group, page)
У нас просто идет проверка слова на сложность и приходит слово со значениями поля difficulty 'easy' или 'hard', в зависимости от раздела словаря делается проверка сложности слов со сложностью которая установлена в редьюсере для данного раздела checkedDifficulty, оно и так если честно довольно запутанно, но боюсь если переименую то ясности это не прибавит, а скорей наоборот.

2021-04-02 15:08 UTC, femiarkh commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
> +              handlerAddWordToList(userId, wordId, 'easy', group, page)
Значит, по хорошему надо менять всю терминологию начиная с редьюсера. Просто у нас в проекте нет такой категории как "лёгкие слова". Есть "изучаемые слова", "сложные слова", "удалённые слова". И эта путанница с терминологией как раз очень усложняет восприятие кода.
Но может это только у меня так, если всем остальным нормально, или привыкли уже, то ладно.

2021-04-06 18:46 UTC, Liza-Veis commented on src/modules/DictionaryPage/components/StatisticModal/StatisticModal.tsx
> +      color: theme.palette.grey[500],
У нас же есть серый цвет в константах, лучше использовать его, чем новый цвет

2021-04-06 18:48 UTC, Liza-Veis commented
Замени все цвета в ModalContent на константы

2021-04-06 18:54 UTC, Liza-Veis commented on src/modules/DictionaryPage/components/StatisticModal/components/ModalContent/styled.ts
> +  /* width: 33%; */
Этот комментарий больше не нужен, так что лучше удалить его

2021-04-06 18:54 UTC, Vadim-Bykov commented on src/modules/DictionaryPage/components/StatisticModal/StatisticModal.tsx
> +      color: theme.palette.grey[500],
Заменил на COLOR_LAYOUT_GRAY

2021-04-06 18:56 UTC, Vadim-Bykov commented on src/modules/DictionaryPage/components/StatisticModal/components/ModalContent/styled.ts
> +  /* width: 33%; */
Удалил. Не знаю почему я это раньше не сделал

2021-04-07 08:50 UTC, Malagor requested changes
Круто поработал. Требуются небольшие корректировки. В частности в порядке вывода блоков. 
Статистику пока оставляй как есть, отдельным ПР поправим.

2021-04-07 08:50 UTC, Malagor commented on src/appConstants/index.ts
> +export const sectionNames = [
Пометь Заглавными и поясни, что за секции, типа DICTIONARY_TOPIC

2021-04-07 08:50 UTC, Malagor commented on src/components/Layout/components/Header/components/PageTitle/PageTitle.tsx
> +        <TimelineIcon
title добавь сюда или внутрь, что бы попап при наведении подсказывал, что это за кнопка

2021-04-07 08:50 UTC, Malagor commented on src/components/WordsList/WordList.tsx
> +  checkedDifficulty: string;
Для этого есть тип в типах 
![image](https://user-images.githubusercontent.com/20399054/113309070-74e6b000-930f-11eb-8330-1c6b1efeb4ba.png)

2021-04-07 08:50 UTC, Malagor commented on src/modules/DictionaryPage/DictionaryPage.tsx
> +    }
Вот тут противоречие со строками 77-98.
Тут ты проверяешь на авторизацию и подгружаешь нужные слова.
Там ты всегда подгружаешь слова авторизованного пользователя. 
Может оно и ничего, так как сюда неавторизованные не должны попасть, но лучше этот момент все же проработать, потому что сейчас ситуация такая 
![image](https://user-images.githubusercontent.com/20399054/113309879-47e6cd00-9310-11eb-924c-2db53aa94446.png)

И второй момент, что ты не проверяешь на наличие ошибки и все равно пытаешься вывести данные.
Как обработать ошибку показано на текстбуке.

2021-04-07 08:50 UTC, Malagor commented on src/modules/DictionaryPage/DictionaryPage.tsx
> +    const nextGroup = group === 5 ? 5 : group + 1;
Эта шутка замениться боковой панелькой переключателя групп

2021-04-07 08:50 UTC, Malagor commented on src/components/Layout/components/Header/components/PageTitle/PageTitle.tsx
> +        <TimelineIcon
Не поправлено. Я имею ввиду атрибут title='settings'

2021-04-07 08:50 UTC, Malagor commented on src/components/WordCard/WordCard.tsx
> +            // showBtnDelete={showBtnDelete}
Удали коммент

2021-04-07 08:50 UTC, Malagor commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
> +  // showBtnDelete: boolean;
Коммент лишний

2021-04-07 08:50 UTC, Malagor commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
> +      marginRight: '14px',
Убери стили кнопок в файл styled, давай тут почистим немного. Если бы у нас не было отдельно файла для стилей, то можно было бы тут эти пару кнопок оставить, но коль уж есть, то давай все стили вместе держать.

2021-04-07 08:50 UTC, Malagor commented on src/components/WordsList/WordList.tsx
> +  checkedDifficulty: string;
Установи правильный тип для `checkedDifficulty`

2021-04-07 08:50 UTC, Malagor commented on src/components/WordsList/WordList.tsx
> +  checkedDifficulty: string;
Кроме того, может назвать этот пропс более понятным, например `excludeDifficulty` например?

2021-04-07 08:50 UTC, Malagor commented on src/components/WordsList/WordList.tsx
> +            word.userWord?.difficulty === checkedDifficulty;
Лучше избегать проверок на отрицание. Ты тут проверяешь на "неподходящее слово", а потом при выводе проверяешь "А не не подходящеее ли это слово"? А можно было бы тут проверить на "Подходящее слово" и если да, то выводим. Тогда и обозвать можно было бы как то типа "isShowWord" или "isCorrectWord".

2021-04-07 08:50 UTC, Malagor commented on src/helpers/dictionaryHelpers.ts
> +  return countWords;
Можно еще извратиться и написать сразу `return arrayWithCount.length ? arrayWithCount[0].count : 0`
А можно еще и от `return `избавиться если сразу в строчку написать.

Это не критично, так на будущее, можешь не исправлять.

2021-04-07 08:50 UTC, Malagor commented on src/modules/DictionaryPage/DictionaryPage.tsx
> +  const classes = useStyles();
перемести наверх к константам, соберем их в более менее одном месте

2021-04-07 08:50 UTC, Malagor commented on src/modules/DictionaryPage/DictionaryPage.tsx
> +          </div>
Вот тут нужно поправить.
Порядок блоков сверху вниз следующий:
Игры
Топики словаря
Пагинация
Карточки.

На мобилке порядок следующий
Игры
Топики слов
Группы
Пагинация 
Карточки

Для этого все блоки нужно обернуть своими обертками и в файле стилей прописать им gridArea и разметить как нужно.
Это все делается в `modules/TextBookPage/styled`
Возможно для страницы словаря нужно будет сделать свою общую обертку с указанием нужных Area. Можно сделать дубликат класса `containerGrid`, назвать его, например, `containerGridDictionary` и там прописать нужную разметку и использовать на этой странице.

Так же поправь порядок и на TextBookPage. В соответствии со списком, что бы было одинаково. Там только про топики не будет

2021-04-07 08:50 UTC, Malagor commented on src/types.ts
> +export type WordSectionType = 'usual' | 'difficult' | 'deleted';
Давай тут тоже константы будем использовать

2021-04-07 08:50 UTC, Malagor commented on src/modules/DictionaryPage/components/Sections/Sections.tsx
> +  ));
Перенеси сразу в ретурн компонента. У нас это единственный возврат, так смысл его в функцию выносить? Размапливай сразу на выводе.

2021-04-07 08:50 UTC, Malagor commented on src/modules/DictionaryPage/components/Sections/Sections.tsx
> +  wordSection: WordSectionType;
Я бы переименовал в `activeSection`, так сразу понятно, что это за пропс такой, а то пришлось прям разбираться.

2021-04-07 08:50 UTC, Malagor commented on src/modules/DictionaryPage/components/Sections/Sections.tsx
> +    let activeItem;
Тут лучше инициализировать сразу в `0` например. Что бы случайно не улетело наружу `undefined`

2021-04-07 08:50 UTC, Malagor commented on src/modules/DictionaryPage/components/StatisticModal/StatisticModal.tsx
> +}))(MuiDialogContent);
Вынеси это в отдельные компоненты.

2021-04-07 08:50 UTC, Malagor commented on src/modules/DictionaryPage/components/StatisticModal/components/ModalContent/ModalContent.tsx
> +import {
Модалка мне что-то совсем не нравиться с точки зрения дизайна. Как Лиза подправит, тогда проверю. Пока оставляем  как есть

2021-04-07 08:50 UTC, Malagor commented on src/modules/TextBookPage/TextBookPage.tsx
> +              />
Коментарий не к этому фрагменту, а к файлу в целом.

Поправь порядок вывода блоков:
```
Игры
Пагинация
Карточки.
```

На мобилке:
```
Игры,
Группы,
Пагинация
Карточки
```

2021-04-07 11:28 UTC, femiarkh commented on src/appConstants/index.ts
> +export const USUAL_SECTION = 'usual';
А что у нас такое `USUAL_SECTION`? Это "Изучаемые" слова? Тогда логичней было бы назвать это `LEARNING_SECTION`.

2021-04-07 11:41 UTC, femiarkh commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
>    const hasWordInList = useIsWordIncluded(wordId);
Вот эти названия переменных тоже загадочные. Про какой тут List идёт речь, куда этот Word инклудед - ничего не понятно. Если это слова, которые, допустим, удалённые и трудные, можно же так и написать.

2021-04-07 11:50 UTC, femiarkh commented on src/components/WordsList/WordList.tsx
> +  const hasWords = words.filter(
Если переменная называется `hasWords`, естественно предположить, что тип данных будет `boolean`. Если речь о количестве слов, то лучше так и указать.

2021-04-07 11:53 UTC, femiarkh commented on src/components/WordsList/WordList.tsx
> +            word.userWord?.difficulty === checkedDifficulty;
А что у нас вообще такое `checkedDifficulty`, и почему, если у пользовательского слова `difficulty` равна ей, то слово считается неподходящим? Вот из-за таких туманных названий переменных код очень сложно читать. Оставляйте комментарии тогда, что ли.

2021-04-07 12:39 UTC, femiarkh commented on src/modules/DictionaryPage/DictionaryPage.tsx
> +      {isLoading && <Loader />}
Лоадер был доработан, но "из коробки" по центру экрана он всё равно не будет. Нужно добавить ему свойство fixed. И ещё он залазит под кнопки. Чтобы этого не происходило, можно поместить его в спозиционированный `div` и задать ему `zIndex`: 
```
<div style={{ position: 'relative', zIndex: 10 }}>
  <Loader fixed />
</div>
```

2021-04-07 13:27 UTC, femiarkh commented on src/modules/DictionaryPage/components/Sections/Sections.tsx
> +      active={i === getActiveSection(i)}
Здесь происходит что-то странное. Зачем каждый раз вызывать `getActiveSection`, и почему номер активного раздела должен зависеть от индекса? У нас текущий активный раздел уже известен - это параметр wordSection. Какому номеру какой раздел соответствует, можно определить, написав простую мапу типа: 
```
 const sectionsMap = {
      [USUAL_SECTION]: 0,
      [DIFFICULT_SECTION]: 1,
      [DELETED_SECTION]: 2,
    };
```
И тогда определение номера активного раздела сведётся к простому `sectionsMap[wordSection]`. Определить его можно заранее, и тогда не придётся вызывать `getActiveSection()` при отрисовке каждого раздела.

2021-04-07 14:52 UTC, Vadim-Bykov commented on src/appConstants/index.ts
> +export const sectionNames = [
Заменил sectionNames на DICTIONARY_TOPICS

2021-04-07 15:30 UTC, Vadim-Bykov commented on src/components/Layout/components/Header/components/PageTitle/PageTitle.tsx
> +        <TimelineIcon
Добавил title='Statistic'

2021-04-07 15:58 UTC, Vadim-Bykov commented on src/components/WordsList/WordList.tsx
> +  checkedDifficulty: string;
Переименовав DifficultyType в ExcludeDifficulty, мне кажется мы больше запутываем (разве мы здесь исключаем), типов на 'hard' и 'easy' у нас нет, поэтому оставил так. Если настаиваешь, то я переименую.

2021-04-07 16:17 UTC, Vadim-Bykov commented on src/modules/DictionaryPage/DictionaryPage.tsx
> +    }
Александр, ты видимо не обновился, т.е. у меня иная ситуация 
![image](https://user-images.githubusercontent.com/70739750/113899854-e58d4100-97d5-11eb-8c11-24cf02481f9a.png)

2021-04-07 16:26 UTC, Vadim-Bykov commented on src/modules/DictionaryPage/components/Sections/Sections.tsx
> +  wordSection: WordSectionType;
Исправил на activeSection.

2021-04-07 16:27 UTC, Vadim-Bykov commented on src/modules/DictionaryPage/components/Sections/Sections.tsx
> +    let activeItem;
Добавил по дефолту 0.

2021-04-07 16:47 UTC, Vadim-Bykov commented on src/modules/DictionaryPage/components/StatisticModal/StatisticModal.tsx
> +}))(MuiDialogContent);
Вынес DialogTitle отдельно.

2021-04-07 16:52 UTC, Vadim-Bykov commented on src/modules/TextBookPage/TextBookPage.tsx
> +              />
Саша, мы об этом уже говорили, что эта верстка Андрея из TextBook. Я пробовал переделать, но у меня пагинация уезжала, договорились что проще Андрею подправить, если я буду ее делать, то придется кардинально ее менять.

2021-04-07 16:55 UTC, Vadim-Bykov commented on src/appConstants/index.ts
> +export const USUAL_SECTION = 'usual';
Исправил на LEARNING_SECTION

2021-04-07 17:50 UTC, Vadim-Bykov commented on src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
>    const hasWordInList = useIsWordIncluded(wordId);
Дима, я исправил бы, но useIsWordIncluded Александр изначально добавлял. Пока не исправляю, просто не понимаю как лучше исправить. Надо на этот счет с Александром посоветоваться
![image](https://user-images.githubusercontent.com/70739750/113911597-d19c0c00-97e2-11eb-9810-e770c8fd537b.png)

2021-04-07 17:55 UTC, Vadim-Bykov commented on src/components/WordsList/WordList.tsx
> +  const hasWords = words.filter(
Переименовал в countWords

2021-04-07 18:09 UTC, Vadim-Bykov commented on src/modules/DictionaryPage/DictionaryPage.tsx
> +      {isLoading && <Loader />}
Спасибо за подсказку. Сделал как ты посоветовал. Он сейчас по центру экрана, но если его можно еще опустить, то было бы еще лучше. 
![image](https://user-images.githubusercontent.com/70739750/113913903-8e8f6800-97e5-11eb-9a49-182b0dbb2184.png)

2021-04-07 18:22 UTC, Vadim-Bykov commented on src/modules/DictionaryPage/components/Sections/Sections.tsx
> +      active={i === getActiveSection(i)}
Переделал на  sectionsMap. Хороший совет

2021-04-07 18:26 UTC, Vadim-Bykov commented on src/modules/DictionaryPage/components/Sections/Sections.tsx
> +    let activeItem;
Исправил на другой манер по совету Димы. Посмотри - наверное так лучше вообще без функции.

2021-04-10 08:40 UTC, Malagor requested changes
Выглядит очень хорошо. 
Подправь оставшиеся комменты и можно будет сливаться.

2021-04-10 08:40 UTC, Malagor commented on src/components/WordsList/WordList.tsx
> +            word.userWord?.difficulty === checkedDifficulty;
Не исправлено

2021-04-10 08:40 UTC, Malagor commented on src/components/WordsList/WordList.tsx
> +              <WordCard
Убери отсюда отрицание

2021-04-10 08:40 UTC, Malagor commented on src/modules/DictionaryPage/DictionaryPage.tsx
> +// import { selectAuthLoadingStatus, selectUserId } from 'modules/Login/selectors';
убери коммент

2021-04-10 08:40 UTC, Malagor commented on src/modules/DictionaryPage/DictionaryPage.tsx
> +  const classes = useStyles();
не исправлено

2021-04-10 08:40 UTC, Malagor commented on src/components/WordsList/WordList.tsx
> +      <StatisticModal />
Кроме `countWords ` стоит еще проверить на процесс загрузки. У ТекстБука есть в стейте такой флажок. Потому что пока идет загрузка слов в списке нет и выводиться сообщение об этом и поверх него лоадер. Выглядит кривенько
![image](https://user-images.githubusercontent.com/20399054/114263752-0b8e2d80-99f0-11eb-83cc-dc4603a7df6e.png)

2021-04-10 08:40 UTC, Malagor commented on src/components/WordsList/WordList.tsx
>      <NoWordsMessage />
Про <NoWordsMessage />
И изменить сообщение на что-то вроде "Не найдено слов для отображения на этой странице".  А то сейчас немного странно звучит, когда переходя в удаленные слова, которых, например, нет, мы, оказывается, всё тут выучили.
![image](https://user-images.githubusercontent.com/20399054/114263844-88210c00-99f0-11eb-9105-5c7af8d94b7c.png)

2021-04-10 17:17 UTC, Vadim-Bykov commented on src/modules/DictionaryPage/DictionaryPage.tsx
> +// import { selectAuthLoadingStatus, selectUserId } from 'modules/Login/selectors';
Убрал

2021-04-10 17:27 UTC, Vadim-Bykov commented on src/components/WordsList/WordList.tsx
> +      <StatisticModal />
Исправил добавлением isLoading 
![image](https://user-images.githubusercontent.com/70739750/114279008-1cb05c00-9a3b-11eb-8f48-faafa881ba34.png)

2021-04-10 17:35 UTC, Vadim-Bykov commented on src/components/WordsList/WordList.tsx
>      <NoWordsMessage />
Исправил на "No words found to display on this page"

2021-04-10 17:47 UTC, Vadim-Bykov commented on src/components/WordsList/WordList.tsx
> +              <WordCard
Заменил название переменной на suitableWord (в методе проверки для получения suitableWord при этом изменил на отрицание) и убрал отсюда отрицание 
![image](https://user-images.githubusercontent.com/70739750/114279546-e58f7a00-9a3d-11eb-9773-a463d24e58e6.png)

2021-04-10 18:12 UTC, Malagor approved these changes

2021-04-10 18:20 UTC, femiarkh approved these changes

2021-04-10 18:20 UTC, merged