RSL-12 user Avatar
Malagor/rs-lang pull request #79
Opened 2021-04-05 19:58 UTC by Andrei107Q

Close #20 

Добавил возможность добавлять аватара для пользователя.
![image](https://user-images.githubusercontent.com/58862645/113619833-249a8580-9662-11eb-8785-785fb1e69de1.png)

Загрузка фото происходит на облачное хранилище Cloudinary, после чего мы получем ссылку на нашу картинку и передаем ее в локальный стейт.
Во время загрузки появляется лоадер и блокируется кнопка отправки формы.
![image](https://user-images.githubusercontent.com/58862645/113619917-485dcb80-9662-11eb-861a-3298f517cb29.png)

2021-04-06 05:34 UTC, femiarkh approved these changes

2021-04-06 05:34 UTC, femiarkh commented on src/components/Layout/components/Header/components/LoginModal/LoginModal.tsx
> +  const [isLoadingImg, steIsLoadingImg] = useState(false);
`set`. И ещё момент: в названиях этих функций is обычно опускают: `setLogin`, `setLoadingImg` и т.п.

2021-04-06 05:34 UTC, femiarkh commented on src/components/Layout/components/Header/components/LoginModal/LoginModal.tsx
> +    console.log('go img');
Зачем оставлять этот лог?

2021-04-06 07:40 UTC, Malagor requested changes
Отлично все сделал. Подправь только комменты.

2021-04-06 07:40 UTC, Malagor commented on src/types.ts
> +};
Это что за типы данных? За что они отвечают? 
Называй переменные так, что бы через месяц не возникало таких вопросов.

2021-04-06 07:40 UTC, Malagor commented on src/components/Layout/components/Header/components/LoginModal/LoginModal.tsx
> +    steIsLoadingImg(true);
что такое `ste`?

2021-04-06 07:40 UTC, Malagor commented on src/components/Layout/components/Header/components/LoginModal/components/Form/Form.tsx
> +  uploadImg: Function;
Какая функция там удет, какие параметры принимает, чтовозвращает? Если нужно указать тип функцию, то можно оформить таким образом
uploadImg: (img: string) => Promise<TypeDataReturnFromPromise>
или
uploadImg: (img: FIleData) => void

2021-04-06 07:40 UTC, Malagor commented on src/types.ts
> +};
Я думаю, эти стили вообще можно отсюда убрать. Они локальные и каждый из них нужен для единственного модуля. Можно там их объявить, тогда даже можно оставить эти же названия и использовать там.

Сюда лучше складывать переиспользуемые типы, которые нужны более чем в одном файле и что бы не писать цепочки путей для импорта типа ../../../../../../../folder/folder/folder/folder/types

2021-04-06 07:40 UTC, Malagor commented on src/components/Layout/components/Header/components/LoginModal/components/Form/components/FileInput/FileInput.tsx
> +            add
Переименуй в add image или add avatar. Что лбы было понятно, что мы так добавляем

2021-04-08 12:12 UTC, Andrei107Q commented on src/components/Layout/components/Header/components/LoginModal/LoginModal.tsx
> +  const [isLoadingImg, steIsLoadingImg] = useState(false);
Окей, спасибо. переименовал `isLoadingImg` и  `isLogin` тоже

2021-04-08 12:22 UTC, Andrei107Q commented on src/types.ts
> +};
`InputsData` переименовал в `SubmitFormData`
`InputsForm` => `InputsFormData`

2021-04-08 13:20 UTC, Andrei107Q commented on src/components/Layout/components/Header/components/LoginModal/LoginModal.tsx
> +    console.log('go img');
не заметил. убрал

2021-04-08 13:22 UTC, Andrei107Q commented on src/components/Layout/components/Header/components/LoginModal/LoginModal.tsx
> +    steIsLoadingImg(true);
должно быть `set` - исправил.

2021-04-08 13:28 UTC, Andrei107Q commented on src/components/Layout/components/Header/components/LoginModal/components/Form/Form.tsx
> +  uploadImg: Function;
спасибо, как раз это хотел спросить. но забыл. исправил

2021-04-08 13:41 UTC, Andrei107Q commented on src/components/Layout/components/Header/components/LoginModal/components/Form/components/FileInput/FileInput.tsx
> +            add
done

2021-04-08 13:44 UTC, Andrei107Q commented on src/types.ts
> +};
окей. сделаю локольно

2021-04-08 15:48 UTC, Malagor approved these changes

2021-04-08 21:01 UTC, merged